"""Alter permissions column to ARRAY(String)

Revision ID: 53a1509a0256
Revises: 001
Create Date: 2025-09-07 16:32:28.100968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a1509a0256'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('target_system', sa.String(length=100), nullable=False),
    sa.Column('mappings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_mappings_tenant_id'), 'code_mappings', ['tenant_id'], unique=False)
    op.create_table('activity_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['workflow_activities.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_executions_activity_id'), 'activity_executions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_executions_workflow_execution_id'), 'activity_executions', ['workflow_execution_id'], unique=False)
    op.create_table('data_table_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_table_rows_table_id'), 'data_table_rows', ['table_id'], unique=False)
    op.create_table('data_table_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('transformation_id', sa.UUID(), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_table_usage_table_id'), 'data_table_usage', ['table_id'], unique=False)
    op.create_index(op.f('ix_data_table_usage_transformation_id'), 'data_table_usage', ['transformation_id'], unique=False)
    op.create_index(op.f('ix_data_table_usage_workflow_id'), 'data_table_usage', ['workflow_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=False),
    sa.Column('target_path', sa.String(length=255), nullable=False),
    sa.Column('source_data_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'DATE', 'DATETIME', 'JSON', name='datatype'), nullable=True),
    sa.Column('target_data_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'DATE', 'DATETIME', 'JSON', name='datatype'), nullable=True),
    sa.Column('transformation_function', sa.String(length=100), nullable=True),
    sa.Column('transformation_params', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mappings_transformation_id'), 'field_mappings', ['transformation_id'], unique=False)
    op.create_table('message_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('segment_type', sa.String(length=10), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_fields', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_segments_message_id'), 'message_segments', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_segments_segment_type'), 'message_segments', ['segment_type'], unique=False)
    op.create_table('transformation_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('is_passing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_tests_transformation_id'), 'transformation_tests', ['transformation_id'], unique=False)
    op.create_table('message_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=100), nullable=False),
    sa.Column('field_number', sa.Integer(), nullable=False),
    sa.Column('component_number', sa.Integer(), nullable=True),
    sa.Column('subcomponent_number', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['message_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_fields_field_path'), 'message_fields', ['field_path'], unique=False)
    op.create_index(op.f('ix_message_fields_message_id'), 'message_fields', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_fields_segment_id'), 'message_fields', ['segment_id'], unique=False)
    op.alter_column('data_tables', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('data_tables', 'schema_definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('data_tables', 'hierarchy_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint('_name_tenant_id_uc', 'data_tables', type_='unique')
    op.drop_index('ix_data_tables_name', table_name='data_tables')
    op.drop_index('ix_data_tables_parent_table_id', table_name='data_tables')
    op.create_index(op.f('ix_hl7_messages_vendor_endpoint_id'), 'hl7_messages', ['vendor_endpoint_id'], unique=False)
    op.create_foreign_key(None, 'hl7_messages', 'vendor_endpoints', ['vendor_endpoint_id'], ['id'])
    op.alter_column(
        'message_transformations',
        'status',
        existing_type=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='messagetransformationstatus'),
        type_=sa.String(length=50),
        existing_nullable=True,
        postgresql_using='status::text'
    )

    op.execute("UPDATE message_transformations SET status = 'processed' WHERE status = 'SUCCESS'")
    op.execute("UPDATE message_transformations SET status = 'failed' WHERE status = 'FAILED'")
    op.execute("UPDATE message_transformations SET status = 'processing' WHERE status = 'PENDING'")

    op.alter_column(
        'message_transformations',
        'status',
        existing_type=sa.String(length=50),
        type_=sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', name='messagestatus'),
        existing_nullable=True,
        postgresql_using='status::messagestatus'
    )
    op.drop_index('ix_message_transformations_source_message_id', table_name='message_transformations')
    op.drop_index('ix_message_transformations_target_message_id', table_name='message_transformations')
    op.drop_index('ix_message_transformations_transformation_id', table_name='message_transformations')
    op.alter_column(
        'users',
        'permissions',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.Text(),
        existing_nullable=True,
        postgresql_using='permissions::text'
    )

    op.execute("""
        UPDATE users SET permissions = REPLACE(REPLACE(REPLACE(permissions::text, '[', '{'), ']', '}'), '"', '') WHERE permissions IS NOT NULL
    """)

    op.alter_column(
        'users',
        'permissions',
        existing_type=sa.Text(),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
        postgresql_using='permissions::varchar[]'
    )
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vendor_endpoints', sa.Column('endpoint_url', sa.String(length=500), nullable=True))
    op.add_column('vendor_endpoints', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.add_column('vendor_endpoints', sa.Column('trigger_workflow_id', sa.UUID(), nullable=True))
    op.add_column('vendor_endpoints', sa.Column('vendor_system_info', sa.JSON(), nullable=True))
    op.add_column('vendor_endpoints', sa.Column('log_full_messages', sa.Boolean(), nullable=False))
    op.add_column('vendor_endpoints', sa.Column('last_message_received_at', sa.DateTime(), nullable=True))
    op.alter_column('vendor_endpoints', 'vendor_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('vendor_endpoints', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'message_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vendor_endpoints', 'max_message_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'rate_limit_per_hour',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'require_ssl',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'total_messages_received',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'total_messages_processed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'total_messages_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_endpoints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_endpoints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_constraint('vendor_endpoints_vendor_slug_key', 'vendor_endpoints', type_='unique')
    op.create_index(op.f('ix_vendor_endpoints_vendor_slug'), 'vendor_endpoints', ['vendor_slug'], unique=False)
    op.create_foreign_key(None, 'vendor_endpoints', 'workflows', ['trigger_workflow_id'], ['id'])
    op.drop_constraint('workflow_executions_execution_id_key', 'workflow_executions', type_='unique')
    op.drop_index('ix_workflow_executions_execution_id', table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    op.create_foreign_key(None, 'workflows', 'vendor_endpoints', ['trigger_endpoint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.create_index('ix_workflow_executions_execution_id', 'workflow_executions', ['execution_id'], unique=False)
    op.create_unique_constraint('workflow_executions_execution_id_key', 'workflow_executions', ['execution_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'vendor_endpoints', type_='foreignkey')
    op.drop_index(op.f('ix_vendor_endpoints_vendor_slug'), table_name='vendor_endpoints')
    op.create_unique_constraint('vendor_endpoints_vendor_slug_key', 'vendor_endpoints', ['vendor_slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('vendor_endpoints', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('vendor_endpoints', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_endpoints', 'total_messages_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'total_messages_processed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'total_messages_received',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'require_ssl',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'rate_limit_per_hour',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'max_message_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'message_format',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vendor_endpoints', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vendor_endpoints', 'vendor_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('vendor_endpoints', 'last_message_received_at')
    op.drop_column('vendor_endpoints', 'log_full_messages')
    op.drop_column('vendor_endpoints', 'vendor_system_info')
    op.drop_column('vendor_endpoints', 'trigger_workflow_id')
    op.drop_column('vendor_endpoints', 'api_key')
    op.drop_column('vendor_endpoints', 'endpoint_url')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'permissions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_message_transformations_transformation_id', 'message_transformations', ['transformation_id'], unique=False)
    op.create_index('ix_message_transformations_target_message_id', 'message_transformations', ['target_message_id'], unique=False)
    op.create_index('ix_message_transformations_source_message_id', 'message_transformations', ['source_message_id'], unique=False)
    op.alter_column('message_transformations', 'status',
               existing_type=sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', name='messagestatus'),
               type_=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='messagetransformationstatus'),
               existing_nullable=True)
    op.drop_constraint(None, 'hl7_messages', type_='foreignkey')
    op.drop_index(op.f('ix_hl7_messages_vendor_endpoint_id'), table_name='hl7_messages')
    op.create_index('ix_data_tables_parent_table_id', 'data_tables', ['parent_table_id'], unique=False)
    op.create_index('ix_data_tables_name', 'data_tables', ['name'], unique=False)
    op.create_unique_constraint('_name_tenant_id_uc', 'data_tables', ['name', 'tenant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('data_tables', 'hierarchy_path',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('data_tables', 'schema_definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('data_tables', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_message_fields_segment_id'), table_name='message_fields')
    op.drop_index(op.f('ix_message_fields_message_id'), table_name='message_fields')
    op.drop_index(op.f('ix_message_fields_field_path'), table_name='message_fields')
    op.drop_table('message_fields')
    op.drop_index(op.f('ix_transformation_tests_transformation_id'), table_name='transformation_tests')
    op.drop_table('transformation_tests')
    op.drop_index(op.f('ix_message_segments_segment_type'), table_name='message_segments')
    op.drop_index(op.f('ix_message_segments_message_id'), table_name='message_segments')
    op.drop_table('message_segments')
    op.drop_index(op.f('ix_field_mappings_transformation_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_index(op.f('ix_data_table_usage_workflow_id'), table_name='data_table_usage')
    op.drop_index(op.f('ix_data_table_usage_transformation_id'), table_name='data_table_usage')
    op.drop_index(op.f('ix_data_table_usage_table_id'), table_name='data_table_usage')
    op.drop_table('data_table_usage')
    op.drop_index(op.f('ix_data_table_rows_table_id'), table_name='data_table_rows')
    op.drop_table('data_table_rows')
    op.drop_index(op.f('ix_activity_executions_workflow_execution_id'), table_name='activity_executions')
    op.drop_index(op.f('ix_activity_executions_activity_id'), table_name='activity_executions')
    op.drop_table('activity_executions')
    op.drop_index(op.f('ix_code_mappings_tenant_id'), table_name='code_mappings')
    op.drop_table('code_mappings')
    # ### end Alembic commands ###
